### PR TITLE
Upgrade EventStore Client API

### LINKED ISSUE #641: Exceptions thrown in EventStore.ClientAPI.NetCore package
Hi! I'm working on a .NET Core project that uses EventFlow with EventStore integration. In our CI pipeline, our end-to-end tests fail regularly with the following exception:

```
[49,00:27:36.110,DEBUG] Deserialization to EventStore.ClientAPI.Messages.ClientMessage+ReadStreamEventsCompleted failed : System.MissingMethodException: No parameterless constructor defined for this object.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at ProtoBuf.Serializers.TypeSerializer.CreateInstance(ProtoReader source, Boolean includeLocalCallback) in C:\code\protobuf-net\src\protobuf-net\Serializers\TypeSerializer.cs:line 314
   at ProtoBuf.Serializers.TypeSerializer.Read(Object value, ProtoReader source) in C:\code\protobuf-net\src\protobuf-net\Serializers\TypeSerializer.cs:line 209
   at ProtoBuf.Meta.TypeModel.DeserializeCore(ProtoReader reader, Type type, Object value, Boolean noAutoCreate) in C:\code\protobuf-net\src\protobuf-net\Meta\TypeModel.cs:line 748
   at ProtoBuf.Meta.TypeModel.Deserialize(Stream source, Object value, Type type, SerializationContext context) in C:\code\protobuf-net\src\protobuf-net\Meta\TypeModel.cs:line 606
   at ProtoBuf.Serializer.Deserialize[T](Stream source) in C:\code\protobuf-net\src\protobuf-net\Serializer.cs:line 84
   at EventStore.ClientAPI.Transport.Tcp.ProtobufExtensions.Deserialize[T](ArraySegment`1 data)
```

This does not seem to be an issue that comes up very often elsewhere. However, I've seen a discussion on https://groups.google.com/forum/#!topic/event-store/aaEXEMFbaGA where the fix was to upgrade the `EventStore.ClientAPI.NetCore` package to an rc version.

The .NET Standard version of the `EventFlow.EventStores.EventStore` package relies on this `EventStore.ClientAPI.NetCore` package. This package is, however, [deprecated](https://github.com/EventStore/ClientAPI.NetCore), and is succeeded by the `EventStore.ClientAPI` package, found in the [EventStore/EventStore](https://github.com/EventStore/EventStore) repo. The .NET Framework version of `EventFlow.EventStores.EventStore` already targets this package (albeit an older version).

The quick fix would be to simply target the new `EventStore.ClientAPI` package, as it's compatible for .NET Standard too. I've tried this and it's working without changing code, but I'm not sure what this means for current installations (the current version of the package is 5.0.1, not sure if this is backwards compatible with EventStore version 4.x).

### PR DESCRIPTION
**Pull request by rutgervanwilligen**
Fixes #641. Not sure whether this brings implications for existing installations.

### CODE REVIEW

**Comment by rutgervanwilligen** [comment]
At first sight, the failed test does not seem to be because of my change. If it is, please let me know if there's anything I can do to fix it!

**Comment by rasmus** [comment]
Rebuilding PR

**Comment by rasmus** [comment]
@rutgervanwilligen could you update the release notes?

**Comment by rutgervanwilligen** [comment]
@rasmus Sorry, I was out of office the past few days -- thanks for merging and updating the release notes as well!

**Comment by rasmus** [comment]
@rutgervanwilligen no worries. I think its great every time someone takes time to create a PR

**Pull request merged**
