### PR TITLE
WIP: Remove .NET Framework

### LINKED ISSUE #713: RFC: Remove .NET Framework
As .NET Framework is rather hard to maintain as it requires Windows to build, I would like some input on whether or not removing .NET Framework from the produced NuGet packages is a good idea at this point.

👍 good idea
👎  bad idea

If you have any comments, please post them below.

### PR DESCRIPTION
**Pull request by rasmus**
Fixes #713

### CODE REVIEW

**Comment by jepperc** [comment]
Hi Rasmus. How about going directly to netcore3.1? 3.0 is already going out of service in 2 months. Maybe just both for compatibility :)
Also, it seems lots of microsoft nuget packages also needs updating, like entityframework core. Currently many issues above netcore 2.2 because of these packages, like #718 .
I am available to do some work.. would you rather I work on this, or fix #718 directly first? (it is a blocker for me)

**Comment by rasmus** [comment]
Hi @jepperc, after doing the PR I got to think a lot about how to move EventFlow forward, especially in regards to a 1.0 release.

The current version of EventFlow as several things that I would differently if I were to write it from scratch today, but fixing these issues would introduce a lot of breaking changes. I know that technically EventFlow hasn't yet passed the 1.0 milestone and in respect to SemVer that means your allowed to do basically anything... this doesn't help the many, many projects that are already using EventFlow.

The middle ground is to treat the 0.x releases as a proper release and make the breaking change moving into 1.x.

Some of the topics of the things I would do differently are

- Not having any .NET Framework version, use .NET Standard 2.0 as the lowest API level. Maybe even on build for LTS versions of .NET in the future
- Use Microsoft.Extensions.Logging throughout EventFlow instead of a custom logger and use proper structured logging
- Use Microsoft.Extensions.DependencyInjection throughout EventFlow instead of having a custom implementation
- Remove all the Owin and old non ASP.NET Core packages

These are some of the things I have been thinking about and then on how to move forward in a way that supports that growing community without making the upgrade path too painful. While still making changes that reflect how .NET 5+ applications would be built.

Currently I thinking about writing all of this down in a road map plan and putting it wither on the docs site, this repo or creating a new repo and then get feedback from the community.

**Comment by rasmus** [comment]
Maybe try to gather all this into the existing milestone...

**Comment by rasmus** [comment]
I created https://github.com/eventflow/EventFlow/issues/724 to outline how to move forward, please comment.

**Comment by rasmus** [comment]
Will be handled by #724

**Pull request closed without merging**
