### PR TITLE
Add example of how to init aggregate's interface

### PR DESCRIPTION
**Pull request by Megadesty**
See EventFlow issue #719

### CODE REVIEW

**Comment by rasmus** [comment]
@Megadesty the CLA isn't signed, thus I cannot merge the PR 😢

**Comment by Megadesty** [comment]
@rasmus Thanks for looking into this PR and of course I could sign the CLA, but I don't think you want to merge this PR anyway because it's a bad hack which only exist to demonstrate my ideas in question #719. So we can just close this PR after the question was discussed.

**Comment by rasmus** [comment]
Hi @Megadesty, thanks for getting back.

I haven't looked at the code yet as the CLA wasn't signed. I'm afraid that if there's something cool in a PR without the CLA signed that I might be tempted to implement my own version of it, or just be inspired to do something similar down the line.

I really try to do all the "license and copyright stuff" by the book.

**Comment by rasmus** [comment]
I had a look at the PR, and I guess as any good IoC container would throw the same exception with better information, I'll not merge it. The custom made IoC container within EventFlow is up for deletion in version 1.0 anyway (see #724).

**Pull request closed without merging**
