### PR TITLE
Fix: Concurrent access to InMemoryEventPersistence

### LINKED ISSUE #444: AggregateException: Collection Was Modified
Hi,

We are trying to setup a test that in parallel will trigger updates on the same aggregate roots.
This will obviously give a number a OptimisticConcurrency retries which is fine.
But sometimes we also see the following stack trace:
stem.AggregateException: One or more errors occurred. (Collection was modified; enumeration operation may not execute.) (Collection was modified; enumeration operation may not execute.) (Collection was modified; enumeration operation may not execute.) ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
    at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EventFlow.EventStores.EventStoreBase.<LoadEventsAsync>d__11`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EventFlow.Aggregates.AggregateRoot`2.<LoadAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EventFlow.Aggregates.AggregateStore.<LoadAsync>d__8`2.MoveNext() in C:\projects\eventflow\Source\EventFlow\Aggregates\AggregateStore.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EventFlow.Aggregates.AggregateStore.<>c__DisplayClass10_0`3.<<UpdateAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at EventFlow.Core.TransientFaultHandler`1.<TryAsync>d__5`1.MoveNext() in C:\projects\eventflow\Source\EventFlow\Core\TransientFaultHandler.cs:line 103

I am making starting the process by calling the aggregateStore.UpdateAsync in multiple threads, which have there own instance resolved.
The only thing that is shared should then be the InMemoryEventStore, could that be the issue here?

### PR DESCRIPTION
**Pull request by frankebersoll**
This fixes #444 

As there is no ImmutableCollection in .NET Standard 1.6, I made an append-only `ImmutableEventCollection` that implements `IReadOnlyCollection` and can be safely returned from `LoadCommittedEventsAsync` without copying it all the time. 

First I tried making it a linked list of lists, so that committing would just append a node with the new events and enumerating would yield all events from the first node up to the current one, ignoring any next nodes, which would effectively make it immutable and enumeration-safe. But that made no difference performance-wise, so I went for the easier implementation that just wraps a list.

I looked into making `CommitEventsAsync` work without locks, but calculating the global sequence number just didn't work: The `ConcurrentDictionary.AddOrUpdate` method can only make atomic updates based on a single aggregate.

This bug happened because an `IReadOnlyCollection` deceives us into being immutable, while even `List<T>` implements it which obviously can be mutated any time.

### CODE REVIEW

**Comment by rasmus** [comment]
@frankebersoll 👍 nice. could you update the release notes and give me a ping when its ready for merge?

**Comment by frankebersoll** [comment]
Ping 👍

**Comment by frankebersoll** [comment]
Test seems to have deadlocked ☹️

**Comment by frankebersoll** [comment]
Maybe we could add a third category of tests for concurrency / indeterministic tests? Or some kind of timeout to those tests? I still don‘t understand what happened in this failing build, and if it was related to the new tests.

**Comment by rasmus** [comment]
@frankebersoll NUnit has support for timeouts but I don't know how to let tests fail due to a timeout and be marked as inconclusive. There's some tests that are marked as `Explicte`, which basically means that you have to specifically ask for those tests to be run. We could mark them as that if they prove problematic.

**Pull request merged**
