### PR TITLE
Firebase read store

### PR DESCRIPTION
**Pull request by warren-pieterse**
# Firebase Realtime Database read store.

## Motivation
To address refreshing read models on the client I've implemented firebase for event flow. It works well for clients like angular2 since all connected clients are notified in real-time when the read model is updated. No need for queues, polling etc.

## Setup
Login to [Firebase console](https://console.firebase.google.com/) and create a project.
Configure the Database rules to allow read and write:
```
{
  "rules": {
    ".read": "true",
    ".write": "true"
  }
}
```
Copy the database url (e.g. https://test-2721e.firebaseio.com/) and update FIREBASE_DATABASE_URL in the EventFlow.Firebase.Tests.IntegrationTests.FirebaseReadModelStoreTests.cs class.

Run the tests in the firebase Category and watch the firebase database update in real-time.

### CODE REVIEW

**Comment by rasmus** [comment]
@warren-pieterse EventFlow uses Paket (https://fsprojects.github.io/Paket/) to mange its NuGet packages

**Comment by rasmus** [comment]
@warren-pieterse Nice, I'm looking forward to seeing this complete 😄

**Comment by warren-pieterse** [comment]
updated to use paket

**Comment by rasmus** [comment]
@warren-pieterse Let me know when its ready for a review

**Comment by warren-pieterse** [comment]
I'm not sure what to do with the firebase database used in the integration
tests. The database (https://event-flow-47b18.firebaseio.com/) is not being
used for anything else, I can add you as an editor to the project so you
can see the effect in firebase.

I still want to create Attribute classes to define indexes, for now I'm
adding them manually to the rules.

You can review what I've done, I'm interested in your feedback.

**Comment by rasmus** [comment]
Closing this as its moved to https://github.com/eventflow/EventFlow.Firebase

**Pull request closed without merging**
