### PR TITLE
Sqlite dbup support

### PR DESCRIPTION
**Pull request by JC008**

### CODE REVIEW

**Comment by JC008** [comment]
Build and all tests work 100% on my side. Not sure what the issue is - guessing its paket related to bring dbup-sqlite on board.

**Comment by JC008** [comment]
All changes and additions except `paket.lock` was submitted.

**Comment by rasmus** [comment]
@JC008 In the build out there's this error on line 1.370. You should also commit the changes to `pack.lock` (https://fsprojects.github.io/Paket/lock-file.html)

```
Connections\SQLiteDatabaseMigrator.cs(32,18): error CS1061: 'SupportedDatabases' does not contain a definition for 'SQLiteDatabase' and no extension method 'SQLiteDatabase' accepting a first argument of type 'SupportedDatabases' could be found (are you missing a using directive or an assembly reference?
```

**Comment by rasmus** [comment]
@JC008 Looks good. Remember to update the release notes and put in the update to `dbup` (look at similar bullets regarding NuGet package updates.

I'll merge it when the build is green and the release notes are updated.

**Comment by JC008** [comment]
Oh poop I messed that pull request up - needed to merge with develop first

**Comment by JC008** [comment]
@rasmus Has 0.27 been merged with develop?

**Comment by rasmus** [comment]
@JC008 Yep, its 6ada11e

**Comment by JC008** [comment]
@rasmus Hang tight - I am working on it

**Comment by rasmus** [comment]
@JC008 There are some merge conflicts

**Comment by rasmus** [comment]
@JC008 Let me know when you are done :smile:

**Comment by JC008** [comment]
@rasmus I am having some problems related to using `SQLite` and `DbUp` using a local build of `0.28.x`. The error reported is `Entry Point not found` when `SQLiteDatabaseMigrator.cs` line 63 is executed in some code of mine. I am guessing the issue relates to the assembly `DbUp` using version 1.0.98.1 of `System.Data.SQLite` and `EventFlow.SQLIte` uses 1.0.99. I tested a downgrade on `EventFlow` on 1.0.98.1 and all the `EventFlow.SQL.Tests` passed but I still need to test my code where I originally found the issue. Will keep you posted - don't merge until I can resolve the issue - even if the builds pass (I am going to push a merge now).

**Comment by JC008** [comment]
A cleaner and fresher pull request is on the way :smile:

**Pull request closed without merging**
