### PR TITLE
Entity Framework on .NET Core 3.1

### LINKED ISSUE #718: MissingMethodException with .Net Core 3.1 and EventFlow-EntityFramework-Integration
Now that the .net core 3 PR is merged and available I tried to upgrade my current project. Unfortunately I have a very weird issue, which I cannot debug any further as I cannot get the EventFlow solution running on my MacBook (I'd debug it there, if it was running).

The exception I get is:

```
System.MissingMethodException: Method not found: 'Microsoft.EntityFrameworkCore.Metadata.Builders.IndexBuilder Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1.HasIndex(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Object>>)'.
   at EventFlow.EntityFramework.Extensions.ModelBuilderExtensions.AddEventFlowSnapshots(ModelBuilder modelBuilder)
```
Same goes for "AddEventFlowEvents"...

The strange thing is: if I skip these both calls and ONLY use my own model builder stuff (for my own entities), then there is no such error - though I also call ```HasIndex``` and such.
And to make it even more strange: putting the code from ```AddEventFlowEvents``` directly into my ModelBuilder-stuff does NOT throw this exception.

About the project: it uses .net core 3.1 and event flow with autofac integration and entity framework integration using postgresql. Unfortunately it is quite impossible to strip out the relevant parts as the project already got quite huge and complex. However - according to the .net core 3.0 api changes I had to do some parts different to the EventFlow examples:

AutoFac: no longer integrated within ```ConfigureServices``` but instead within ```ConfigureContainer``` being a void method.

```
public void ConfigureContainer(ContainerBuilder builder)
{
    // ...
    EventFlowOptions.New
                .Configure(options => options.IsAsynchronousSubscribersEnabled = true)
                .UseAutofacContainerBuilder(builder)
                .ConfigureEntityFramework(EntityFrameworkConfiguration.New)
                .UseHangfireJobScheduler()
                .PublishToRabbitMq(RabbitMqConfiguration.With(new Uri(this.Configuration["RabbitMQ:Url"]),
                    exchange: this.Configuration["RabbitMQ:Exchange"]))
                .UseLibLog(LibLogProviders.Serilog);
                //.CreateContainer();
} 
```
Note the point not calling ```CreateContainer()```, which threw exceptions. Obviously .net core 3 does it on its own... or at least the relevant stuff, which is done within this method.

### PR DESCRIPTION
**Pull request by frankebersoll**
This adds multi-targeting for EventFlow.EntityFramework: For `netcoreapp3.1` targets we now use Entity Framework 3.1.1.

Fixes #718

### CODE REVIEW

**Comment by frankebersoll** [comment]
We had some failing tests because of version mismatches:

```
System.MissingMethodException : Method not found: 'System.Reflection.MethodInfo Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.get_SelectAsyncMethod()
```

[Solution at StackOverflow](https://stackoverflow.com/a/53132043/4317569)

**Comment by rasmus** [comment]
@frankebersoll I released `master` (last one failed) and retried the build on this one. Is this still WIP?

**Comment by frankebersoll** [comment]
@rasmus The build is passing, so this can be merged 👍

**Comment by rasmus** [comment]
@frankebersoll  you closed the pull request, was that a mistake?

**Comment by frankebersoll** [comment]
I started cleaning up my fork and deleted this branch in the process. Yes, it was a mistake.

**Pull request merged**
