### PR TITLE
mongoDB ReadModelStore as IQueryable

### PR DESCRIPTION
**Pull request by FillScheers**
give the option to query a mongodb read model store as an IQueryable

### CODE REVIEW

**Comment by rasmus** [comment]
Nice, just a few comments

- update to latest develop
- write a test
- add a line to the release notes

**Comment by FillScheers** [comment]
Will do

**Comment by FillScheers** [comment]
i dit not know how to test it correctly so i just tried to make one.

hope it is good

**Comment by FillScheers** [comment]
just found out that mdlint  changed the markdown fixing it now

**Comment by rasmus** [comment]
Nice thanks, will merge when build is green 😄

**Pull request merged**
