### PR TITLE
WIP: #515 Upgrade NEST to 6.1.0 and Newtonsoft to 11.0.2

### PR DESCRIPTION
**Pull request by poumup**

### CODE REVIEW

**Comment by poumup** [comment]
Someone can check the PR ?

**Comment by rasmus** [comment]
The build is failing for some reason, I have merged develop in and if it continues then I'll have a look this evening.

You still lack signing til CLA, it is required before I can accept any PRs.

**Comment by poumup** [comment]
CLA signing is done

**Comment by rasmus** [comment]
@poumup the problem seems to be the assembly redirects

**Comment by rasmus** [comment]
Its basically these few lines in the app.configs

```xml
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-65535.65535.65535.65535" newVersion="10.0.0.0"/>
      </dependentAssembly>
```

**Comment by poumup** [comment]
Thank for help. I will this sone as possible

**Comment by rasmus** [comment]
Seems the issue now is real ES errors due to the upgrade

**Comment by idubnori** [comment]
@poumup I've resolved the conflict, changed ES docker image version to 6.3.2 and fixed a clear mistake. It seems still have [three tests failed](https://ci.appveyor.com/project/idubnori/eventflow/build/0.65.248/tests). Could you merge [this PR](https://github.com/poumup/EventFlow/pull/1) and go forward? Hope this helps.

**Comment by idubnori** [comment]
poumup/EventFlow#1

**Comment by rasmus** [comment]
You added a `-la` file that's 13K long. Please delete that and if that's in the PR I'll have to squash merge to develop. If you could delete the file and do a force update for the branch

**Comment by rasmus** [comment]
The PR seems a little weird, did you branch of develop?

**Comment by poumup** [comment]
close this PR. follow this PR #535

**Pull request closed without merging**
